In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd



print (tf.__version__)

1.9.0

In [2]:
tf.enable_eager_execution()

In [3]:
boston_housing = keras.datasets.boston_housing

(train_data, train_labels), (test_data, test_labels) = boston_housing.load_data()

In [4]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
                'TAX', 'PTRATIO', 'B', 'LSTAT']

df = pd.DataFrame(data=train_data, columns=column_names)
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72
1,0.02177,82.5,2.03,0.0,0.415,7.610,15.7,6.2700,2.0,348.0,14.7,395.38,3.11
2,4.89822,0.0,18.10,0.0,0.631,4.970,100.0,1.3325,24.0,666.0,20.2,375.52,3.26
3,0.03961,0.0,5.19,0.0,0.515,6.037,34.5,5.9853,5.0,224.0,20.2,396.90,8.01
4,3.69311,0.0,18.10,0.0,0.713,6.376,88.4,2.5671,24.0,666.0,20.2,391.43,14.65

In [5]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000
mean,3.745111,11.480198,11.104431,0.061881,0.557356,6.267082,69.010644,3.740271,9.440594,405.898515,18.475990,354.783168,12.740817
std,9.240734,23.767711,6.811308,0.241238,0.117293,0.709788,27.940665,2.030215,8.698360,166.374543,2.200382,94.111148,7.254545
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,188.000000,12.600000,0.320000,1.730000
25%,0.081437,0.000000,5.130000,0.000000,0.453000,5.874750,45.475000,2.077100,4.000000,279.000000,17.225000,374.672500,6.890000
50%,0.268880,0.000000,9.690000,0.000000,0.538000,6.198500,78.500000,3.142300,5.000000,330.000000,19.100000,391.250000,11.395000
75%,3.674808,12.500000,18.100000,0.000000,0.631000,6.609000,94.100000,5.118000,24.000000,666.000000,20.200000,396.157500,17.092500
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.725000,100.000000,10.710300,24.000000,711.000000,22.000000,396.900000,37.970000

In [6]:
df.corr()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
CRIM,1.000000,-0.192179,0.397419,-0.050828,0.405765,-0.217597,0.344410,-0.378590,0.609689,0.575652,0.273447,-0.390613,0.434384
ZN,-0.192179,1.000000,-0.533823,-0.041981,-0.521713,0.338683,-0.578728,0.650787,-0.311091,-0.303522,-0.403139,0.176006,-0.415237
INDUS,0.397419,-0.533823,1.000000,0.052839,0.774200,-0.409924,0.656350,-0.725155,0.599226,0.701362,0.379284,-0.372885,0.603129
CHAS,-0.050828,-0.041981,0.052839,1.000000,0.079803,0.040431,0.080488,-0.083101,-0.024851,-0.051343,-0.122008,0.037832,-0.011017
NOX,0.405765,-0.521713,0.774200,0.079803,1.000000,-0.335866,0.729338,-0.777062,0.616535,0.673471,0.188160,-0.409479,0.592994
RM,-0.217597,0.338683,-0.409924,0.040431,-0.335866,1.000000,-0.240875,0.233970,-0.243990,-0.307904,-0.367256,0.145525,-0.610844
AGE,0.344410,-0.578728,0.656350,0.080488,0.729338,-0.240875,1.000000,-0.766670,0.462188,0.512746,0.282193,-0.278403,0.590898
DIS,-0.378590,0.650787,-0.725155,-0.083101,-0.777062,0.233970,-0.766670,1.000000,-0.511179,-0.543668,-0.243067,0.295995,-0.507075
RAD,0.609689,-0.311091,0.599226,-0.024851,0.616535,-0.243990,0.462188,-0.511179,1.000000,0.922676,0.449908,-0.478245,0.490250
TAX,0.575652,-0.303522,0.701362,-0.051343,0.673471,-0.307904,0.512746,-0.543668,0.922676,1.000000,0.440499,-0.471777,0.534752
PTRATIO,0.273447,-0.403139,0.379284,-0.122008,0.188160,-0.367256,0.282193,-0.243067,0.449908,0.440499,1.000000,-0.178060,0.365873
B,-0.390613,0.176006,-0.372885,0.037832,-0.409479,0.145525,-0.278403,0.295995,-0.478245,-0.471777,-0.178060,1.000000,-0.376081
LSTAT,0.434384,-0.415237,0.603129,-0.011017,0.592994,-0.610844,0.590898,-0.507075,0.490250,0.534752,0.365873,-0.376081,1.000000


**Attributes**
- CRIM:    per capita crime rate by town.
- ZN:      proportion of residential land zoned for lots over 25,000 sq.ft.
- INDUS:   proportion of non-retail business acres per town.
- CHAS:    Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).
- NOX:     nitric oxides concentration (parts per 10 million).
- RM:      average number of rooms per dwelling.
- AGE:     proportion of owner-occupied units built prior to 1940.
- DIS:     weighted distances to ﬁve Boston employment centers.
- RAD:     index of accessibility to radial highways.
- TAX:     full-value property-tax rate per 10,000 dollars.
- PTRATIO: pupil-teacher ratio by town.
- B:       1000(Bk−0.63)^2 where Bk is the proportion of blacks by town.
- LSTAT:   Percent lower status of the population.
- MEDV:    Median value of owner-occupied homes in thousand dollars.

In [7]:
mean = np.array(df.mean())
std = np.array(df.std())

In [8]:
x_train = (train_data - mean) / std
x_test = (test_data - mean) / std

In [9]:
df_norm = pd.DataFrame(x_train, columns=column_names)
df_norm['Y'] = train_labels
df_norm.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
0,-0.271909,-0.483017,-0.435222,-0.256515,-0.165022,-0.176224,0.812055,0.116554,-0.625474,-0.594433,1.147078,0.447522,0.824198,15.2
1,-0.402927,2.988079,-1.332260,-0.256515,-1.213677,1.892000,-1.907995,1.246040,-0.855402,-0.348001,-1.716061,0.431371,-1.327556,42.3
2,0.124785,-0.483017,1.027052,-0.256515,0.627864,-1.827422,1.109113,-1.185969,1.673810,1.563349,0.783505,0.220344,-1.306880,50.0
3,-0.400996,-0.483017,-0.868325,-0.256515,-0.361112,-0.324156,-1.235140,1.105809,-0.510509,-1.093307,0.783505,0.447522,-0.652118,21.1
4,-0.005627,-0.483017,1.027052,-0.256515,1.326967,0.153452,0.693948,-0.577856,1.673810,1.563349,0.783505,0.389399,0.263171,17.7

In [10]:
df_norm_test = pd.DataFrame(x_test, columns=column_names)
df_norm_test['Y'] = test_labels

In [11]:
batch_size = 8
epochs = 30

(This is not needed anymore: via tf.estimators.inputs...)
```python
def input_fn(df, label_key, num_epochs=10, batch_size=32, shuffle=True):
    # Is this part needed??
    labels = df[label_key]
    
    # slice the dictionary representation of the pandas dataframe
    ds = tf.data.Dataset.from_tensor_slices((dict(df), labels))
    
    # Shuffle if needed
    if shuffle: ds.shuffle(1000)
        
    # split into batches and epochs    
    ds = ds.batch(batch_size).repeat(num_epochs)
    
    # return the dataset
    return ds
```

  ```python
# Are these needed???
CRIM = tf.feature_column.numeric_column('CRIM')
ZN = tf.feature_column.numeric_column('ZN')
INDUS = tf.feature_column.numeric_column('INDUS')
CHAS = tf.feature_column.numeric_column('CHAS')
NOX = tf.feature_column.numeric_column('NOX')
RM = tf.feature_column.numeric_column('RM')
AGE = tf.feature_column.numeric_column('AGE')
DIS = tf.feature_column.numeric_column('DIS')
RAD = tf.feature_column.numeric_column('RAD')
TAX = tf.feature_column.numeric_column('TAX')
PTRATIO = tf.feature_column.numeric_column('PTRATIO')
B = tf.feature_column.numeric_column('B')
LSTAT = tf.feature_column.numeric_column('LSTAT')

my_fc = [CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX, PTRATIO, B, LSTAT]
```

In [12]:
my_fc = [tf.feature_column.numeric_column(x) for x in df_norm.keys()]
print (my_fc)

[_NumericColumn(key='CRIM', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='ZN', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='INDUS', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='CHAS', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='NOX', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='RM', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='AGE', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='DIS', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='RAD', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='TAX', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='PTRATIO', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='B', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='LSTAT', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='Y', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [13]:
estimator = tf.estimator.DNNRegressor(
    hidden_units=[32,16],
    feature_columns=my_fc,
    model_dir='./DNN',
    weight_column=None,
    optimizer='Adagrad',
    activation_fn=tf.nn.relu,
    dropout=0.25,
    input_layer_partitioner=None,
    config=None
)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './DNN', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000000CF2F438>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [14]:
# make the input_fn for the training
input_fn_train = tf.estimator.inputs.numpy_input_fn(
      x=dict(df_norm),
      y=np.array(train_labels),
      num_epochs=None,
      shuffle=True)

In [15]:
# make the input_fn for the testing
input_fn_test = tf.estimator.inputs.numpy_input_fn(
      x=dict(df_norm_test),
      y=np.array(test_labels),
      num_epochs=1,
      shuffle=True)

In [16]:
train_spec = tf.estimator.TrainSpec(input_fn=input_fn_train,
                                    max_steps=5000)
eval_spec = tf.estimator.EvalSpec(input_fn=input_fn_test)

In [17]:
tf.estimator.train_and_evaluate(estimator=estimator,
                                train_spec=train_spec,
                                eval_spec=eval_spec
                                )

INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after 600 secs (eval_spec.throttle_secs) or training is finished.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./DNN\model.ckpt.
INFO:tensorflow:loss = 58144.26, step = 1
INFO:tensorflow:global_step/sec: 39.509
INFO:tensorflow:loss = 3777.2651, step = 101 (2.530 sec)
INFO:tensorflow:global_step/sec: 44.9191
INFO:tensorflow:loss = 3647.1865, step = 201 (2.241 sec)
INFO:tensorflow:global_step/sec: 37.8497
INFO:tensorflow:loss = 4729.9077, step = 301 (2.642 sec)
INFO:tensorflow:global_step/sec: 32.6794
INFO:tensorflow:loss = 3483.392, step = 401 (3.044 sec)
INFO:tensorflow:global_step/sec: 35.08
INFO:tensorflow:loss = 3857.3826, step = 501 (2.866 sec)
INFO:tensorflow:global_step/sec: 34.2062
INFO:tensorflow:loss = 3492.1343, step = 601 (2.908 sec)
INFO:tensorflow:global_step/sec: 42.3642
INFO:tensorflow:loss = 2808.154, step = 701 (2.360 sec)
INFO:tensorflow:global_step/sec: 38.4755
INFO:tensorflow:loss = 3471.2576, step = 801 (2.615 sec)
INFO:tensorflow:global_step/sec: 36.7643
INFO:tensorflow:loss = 3525.2466, step = 901 (2.720 sec)
INFO:tensorflow:global_step/sec: 35.8137
INFO:tensorflow:loss = 3050.245, step = 1001 (2.792 sec)
INFO:tensorflow:global_step/sec: 31.8529
INFO:tensorflow:loss = 2720.9314, step = 1101 (3.124 sec)
INFO:tensorflow:global_step/sec: 31.3473
INFO:tensorflow:loss = 3775.0093, step = 1201 (3.190 sec)
INFO:tensorflow:global_step/sec: 46.1021
INFO:tensorflow:loss = 3608.7112, step = 1301 (2.174 sec)
INFO:tensorflow:global_step/sec: 49.6928
INFO:tensorflow:loss = 2682.6416, step = 1401 (2.015 sec)
INFO:tensorflow:global_step/sec: 32.4165
INFO:tensorflow:loss = 3925.99, step = 1501 (3.092 sec)
INFO:tensorflow:global_step/sec: 30.3009
INFO:tensorflow:loss = 2821.2822, step = 1601 (3.285 sec)
INFO:tensorflow:global_step/sec: 35.5438
INFO:tensorflow:loss = 2412.6562, step = 1701 (2.813 sec)
INFO:tensorflow:global_step/sec: 34.4302
INFO:tensorflow:loss = 2510.8823, step = 1801 (2.920 sec)
INFO:tensorflow:global_step/sec: 43.5346
INFO:tensorflow:loss = 2281.0435, step = 1901 (2.281 sec)
INFO:tensorflow:global_step/sec: 37.4667
INFO:tensorflow:loss = 3837.1128, step = 2001 (2.669 sec)
INFO:tensorflow:global_step/sec: 30.7084
INFO:tensorflow:loss = 2782.1333, step = 2101 (3.272 sec)
INFO:tensorflow:global_step/sec: 32.5368
INFO:tensorflow:loss = 2621.2795, step = 2201 (3.073 sec)
INFO:tensorflow:global_step/sec: 38.747
INFO:tensorflow:loss = 2469.6248, step = 2301 (2.565 sec)
INFO:tensorflow:global_step/sec: 34.4396
INFO:tensorflow:loss = 2025.6364, step = 2401 (2.904 sec)
INFO:tensorflow:global_step/sec: 45.9555
INFO:tensorflow:loss = 2960.1465, step = 2501 (2.207 sec)
INFO:tensorflow:global_step/sec: 31.279
INFO:tensorflow:loss = 2963.3423, step = 2601 (3.166 sec)
INFO:tensorflow:global_step/sec: 33.3842
INFO:tensorflow:loss = 2350.785, step = 2701 (2.995 sec)
INFO:tensorflow:global_step/sec: 32.4882
INFO:tensorflow:loss = 2239.9854, step = 2801 (3.086 sec)
INFO:tensorflow:global_step/sec: 32.2848
INFO:tensorflow:loss = 2741.7896, step = 2901 (3.105 sec)
INFO:tensorflow:global_step/sec: 42.2079
INFO:tensorflow:loss = 1568.064, step = 3001 (2.354 sec)
INFO:tensorflow:global_step/sec: 32.9291
INFO:tensorflow:loss = 2317.3823, step = 3101 (3.037 sec)
INFO:tensorflow:global_step/sec: 32.7457
INFO:tensorflow:loss = 1970.8472, step = 3201 (3.061 sec)
INFO:tensorflow:global_step/sec: 33.2886
INFO:tensorflow:loss = 2048.1143, step = 3301 (2.997 sec)
INFO:tensorflow:global_step/sec: 29.7687
INFO:tensorflow:loss = 3564.9436, step = 3401 (3.375 sec)
INFO:tensorflow:global_step/sec: 35.8009
INFO:tensorflow:loss = 2583.228, step = 3501 (2.778 sec)
INFO:tensorflow:global_step/sec: 42.4805
INFO:tensorflow:loss = 2118.4807, step = 3601 (2.370 sec)
INFO:tensorflow:global_step/sec: 32.3621
INFO:tensorflow:loss = 2181.9226, step = 3701 (3.074 sec)
INFO:tensorflow:global_step/sec: 30.7405
INFO:tensorflow:loss = 2210.6177, step = 3801 (3.265 sec)
INFO:tensorflow:global_step/sec: 39.8859
INFO:tensorflow:loss = 2017.2363, step = 3901 (2.500 sec)
INFO:tensorflow:global_step/sec: 47.3177
INFO:tensorflow:loss = 3015.2705, step = 4001 (2.114 sec)
INFO:tensorflow:global_step/sec: 38.3947
INFO:tensorflow:loss = 2798.4954, step = 4101 (2.614 sec)
INFO:tensorflow:global_step/sec: 47.8229
INFO:tensorflow:loss = 1883.3177, step = 4201 (2.107 sec)
INFO:tensorflow:global_step/sec: 42.1078
INFO:tensorflow:loss = 2999.538, step = 4301 (2.359 sec)
INFO:tensorflow:global_step/sec: 39.1009
INFO:tensorflow:loss = 1859.8162, step = 4401 (2.543 sec)
INFO:tensorflow:global_step/sec: 30.6595
INFO:tensorflow:loss = 2350.3027, step = 4501 (3.261 sec)
INFO:tensorflow:global_step/sec: 37.8346
INFO:tensorflow:loss = 2268.9214, step = 4601 (2.659 sec)
INFO:tensorflow:global_step/sec: 32.6364
INFO:tensorflow:loss = 3883.3767, step = 4701 (3.048 sec)
INFO:tensorflow:global_step/sec: 40.1957
INFO:tensorflow:loss = 3221.4558, step = 4801 (2.503 sec)
INFO:tensorflow:global_step/sec: 43.4043
INFO:tensorflow:loss = 1835.4556, step = 4901 (2.293 sec)
INFO:tensorflow:Saving checkpoints for 5000 into ./DNN\model.ckpt.
INFO:tensorflow:Loss for final step: 1918.8539.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-08-13-20:11:41
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./DNN\model.ckpt-5000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-08-13-20:11:41
INFO:tensorflow:Saving dict for global step 5000: average_loss = 1.961967, global_step = 5000, loss = 200.12064
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5000: ./DNN\model.ckpt-5000

({'average_loss': 1.961967, 'loss': 200.12064, 'global_step': 5000}, [])